# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Feature request
description: Missing functionality? Come tell us about it!
labels:
  - kind/enhancement
  - status/triage

body:
  - type: checkboxes
    attributes:
      label: This is a feature that ...
      description: |
        Make sure that your request fulfills all of the following requirements.
        If one requirement cannot be satisfied, explain in detail why.
      options:
        - label: ... the existing functionality does not satisfy my request
        - label: ... is not a duplicate of any open or closed issues
        - label: ... is not a question or discussion topic

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the feature you want to see?
    validations:
      required: true

